image: osrf/ros:galactic-desktop
options:
  max-time: 5  # Pipeline will fail after 5 minutes

definitions:
  steps:
    - step: &build
        name: 'Build and Test Package'
        script:
          - apt-get -y update && apt-get install -y openssh-client
          - source /opt/ros/galactic/setup.bash
          - git submodule update --init --recursive --remote
          - rosdep update --rosdistro=galactic
          - rosdep install --from-paths . --ignore-src --rosdistro galactic -y -r
          - colcon build --continue-on-error
          - colcon test
          - colcon test-result --verbose
        artifacts:
          - build/**
          - log/**
          - install/**
          - docs/**

pipelines:
  pull-requests:
    "**":
    - step: *build
